version: '3.6'

services:
  backend_java:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 8080:8080
    network_mode: host

  database_tecweb:
    image: mysql
    container_name: tecweb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'tecweb'
      MYSQL_PASSWORD: 'tecweb'
      MYSQL_DATABASE: 'tecweb'
    network_mode: host

  frontend_angular:
    build: ./frontend
    container_name: ang_front
    volumes:
      - ./frontend:/app/frontend
    network_mode: host
