spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tecweb?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: tecweb
    password: tecweb
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api/v1
